<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [3]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [4]:
greeting("Super Man")

'Hello Super Man!'

In [5]:
greeting(name="Super Man")

'Hello Super Man!'

In [6]:
greet=greeting(name='Super Man')
print(greet)

Hello Super Man!


In [10]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

In [14]:
list_min, list_max, list_mean = basic_stats([1,2,3,4,5])

### 1.2 Named functions that don’t return

### 1.3 Anonymous functions

In [17]:
my_short_function = lambda name: f"Hello {name}!"

my_short_function(name="Super Man")

'Hello Super Man!'

In [19]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [20]:
sorted(numbers, key=lambda x:x[1])

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [21]:
sorted(numbers, key=lambda x: sum(x))

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [22]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So nice to meet you!'
    else:
        return f'Hello {name}!'

In [23]:
greeting()

'Hello no one!'

In [25]:
print('I', 'am', 'Batman!')

I am Batman!


In [26]:
print('I', 'am', 'Batman!', sep="---")

I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

In [ ]:

# Your code here


### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

if name = 'Batman', code will give 'Hello Batman! So, nice to meet you!'
if not it will return 'Hello {name}!'
the else statement does not affect the function of the code

## Exercise 2 :  Calculator functions

In [32]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

In [36]:
import numpy as np
def add(x,y):
    x = np.array(x)
    y = np.array(y)
    return x + y

add(x,y)

array([100, 100, 100, 100, 100])

In [37]:
def subtract(x, y):
    x = np.array(x)
    y = np.array(y)
    return x - y

subtract(x, y)

array([-28, -32, -12,  52, -46])

In [38]:
def multiply(x, y):
    x = np.array(x)
    y = np.array(y)
    return x*y

multiply(x, y)


array([2304, 2244, 2464, 1824, 1971])

In [43]:
def divide(x, y):
    x = np.array(x)
    y = np.array(y)
    if np.any(y==0):
        return 'Error'
    return x/y

divide(x, y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

## Exercise 3 :  max_info() with NumPy

In [53]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

def max_info(numbers):
    numbers = np.array(numbers)
    return np.max(numbers), np.argmax(numbers)


In [54]:
np.max(numbers)

83

In [55]:
np.argmax(numbers)

2