<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [5]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x=py_list

### 1.2 Subsetting by masking (Arrays only)

In [6]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [7]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [9]:
np_array[~(np_array > 3)]

array([1, 2, 3])

In [10]:
np_array[(np_array > 3) & (np_array < 8)] 

array([4, 5, 6, 7])

In [11]:
np_array[(np_array < 3) | (np_array > 8)]

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [12]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [13]:
py_list_2d[3]

[4, 'D']

In [14]:
py_list_2d[3][0]

4

In [15]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [16]:
py_list_2d[:3][0]

[1, 'A']

In [17]:
py_list_2d[3:6][0]

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [18]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [19]:
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

In [20]:
np_array_2d[3, 0]

'4'

In [21]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [22]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [23]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

In [24]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [25]:
x=[1]*10

x

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [32]:
x=[1]
x=x + [2]
x=x + [3]
x=x + [4]

x

[1, 2, 3, 4]

In [34]:
x=[1]
x=x + [2,3,4]
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [36]:
a = (1,2,3)

print(a[0])

1


In [38]:
a[0]+=[10]

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

### 2.2 Be VERY careful when copying

In [39]:
x = [1,2,3]
y=x
z=x


In [40]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

| **Term**    |  **Brief description**   |
| :--- | :--- |
| Subsetting   |  means to select specific data from a list  |
| Indexing   |  means to select only 1 element from a list  |
| Slicing   |  means to select more than 1 element from a list  |
| Masking   | masking allows us to select only data that are 'True'   |

## Exercise 2 :  Show me the ‘odd’ letters

In [76]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_number = np_array_2d[0:10,0]
np_int = np_number.astype(int)

np_divide=np_int%2

np_divide == 1

np_array_2d[np_divide == 1, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')