<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

In [1]:
import numpy as np

### 1.1 Let’s compare

In [11]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [12]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [13]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [14]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [15]:
print(py_real_names[0])

Natasha Romanoff


In [16]:
print(py_super_names[0])

Black Widow


In [17]:
print(py_super_names[2]) 

Doctor Strange


In [18]:
print(py_super_names[-1])

Doctor Strange


### 1.3 Accessing data from a dictionary

In [19]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

In [22]:
print(superhero_info["Natasha Romanoff"])

Black Widow


In [23]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [24]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [25]:
py_superhero_info=[['Natasha Romanoff', 'Black Widow'],['Tony Stark', 'Iron Man'], ['Stephen Strange', 'Doctor Strange']]

In [28]:
print(py_superhero_info[1])


['Tony Stark', 'Iron Man']


## 2 Lists vs. Arrays

### 2.1 Size

In [29]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [30]:
len(py_list_2d)

10

In [31]:
len(np_array_2d)

10

In [32]:
np_array_2d.shape

(10, 2)

### 2.2 Arrays are fussy about type

In [33]:
py_list = [1, 1.5, 'A']
np.array(py_list)


array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [36]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)       

np_array

array([1, 2, 3, 4, 5])

In [37]:
py_list + 10

TypeError: can only concatenate list (not "int") to list

In [38]:
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [39]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [41]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [42]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [44]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [45]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [46]:
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [47]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [48]:
py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [49]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [50]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [51]:
py_list ==3

False

In [52]:
py_list>3

TypeError: '>' not supported between instances of 'list' and 'int'

In [53]:
np_array ==3

array([False, False,  True, False, False])

In [54]:
np_array >3

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [55]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [56]:
sum(py_list)

15

In [57]:
max(py_list)

5

In [58]:
np_array.sum()

15

## Exercise 1 :  Total recall?

1. 
both of them can be used to store data
_both have values that start from 0_

2. 
operation on a list looks at the list as a whole while operation on an array works on its individual data
arrays can only have a single data type while lists can have multiple data type

3.
dictionary has a key and value, it allows us to condense 2 lists/arrays into a single code


## Exercise 2 :  Index me

In [5]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0], py_list[2], py_list[4], py_list[6], py_list[8])

a1 c3 e5 g7 i9


## Exercise 3 :  Capitalise Heros

In [10]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()

superhero_info['Stephen Strange']

'DOCTOR STRANGE'

## Exercise 4 :  How many ones

In [23]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61] 

np_numbers = np.array(numbers)

(np_numbers == 1).sum()


2